//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazeMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazeMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActiveRegion {
            get {
                object obj = ResourceManager.GetObject("ActiveRegion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Adding Floors
        ///			&lt;br /&gt;
        ///			&lt;br /&gt;
        ///To create floors, select the &quot;Floor&quot; tool and click two locations in the Maze Editor pane to define a rectangular floor between them.&lt;br /&gt;&lt;br /&gt;
        ///To buil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddingFloors {
            get {
                return ResourceManager.GetString("AddingFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Adding Walls
        ///			&lt;br /&gt;
        ///			&lt;br /&gt;
        ///To build walls, select the &quot;Wall&quot; tool and click two locations in the Maze Editor pane to build a wall between them&lt;br /&gt;&lt;br /&gt;
        ///Further clicking will buil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddingWalls {
            get {
                return ResourceManager.GetString("AddingWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; &lt;a href=&quot;Textures.htm&quot;&gt;Textures&lt;/a&gt; &amp;gt; Applying Textures
        ///			&lt;br /&gt;
        ///			&lt;br /&gt;
        ///			Once you have added a texture to the &lt;a href=&quot;Texturecollection.htm&quot;&gt;Texture Collection&lt;/a&gt;, you can apply [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Applyingtextures {
            get {
                return ResourceManager.GetString("Applyingtextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arr_down {
            get {
                object obj = ResourceManager.GetObject("arr_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arr_up {
            get {
                object obj = ResourceManager.GetObject("arr_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AudioCollectionIcon {
            get {
                object obj = ResourceManager.GetObject("AudioCollectionIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blank1 {
            get {
                object obj = ResourceManager.GetObject("Blank1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bulb1 {
            get {
                object obj = ResourceManager.GetObject("bulb1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCenter {
            get {
                object obj = ResourceManager.GetObject("buttonCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCenter_mouseover {
            get {
                object obj = ResourceManager.GetObject("buttonCenter_mouseover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonCenter_onclick {
            get {
                object obj = ResourceManager.GetObject("buttonCenter_onclick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonDown {
            get {
                object obj = ResourceManager.GetObject("buttonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonDown_mouseover {
            get {
                object obj = ResourceManager.GetObject("buttonDown_mouseover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonDown_onclick {
            get {
                object obj = ResourceManager.GetObject("buttonDown_onclick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonLeft {
            get {
                object obj = ResourceManager.GetObject("buttonLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonLeft_mouseover {
            get {
                object obj = ResourceManager.GetObject("buttonLeft_mouseover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonLeft_onclick {
            get {
                object obj = ResourceManager.GetObject("buttonLeft_onclick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonRight {
            get {
                object obj = ResourceManager.GetObject("buttonRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonRight_mouseover {
            get {
                object obj = ResourceManager.GetObject("buttonRight_mouseover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonRight_onclick {
            get {
                object obj = ResourceManager.GetObject("buttonRight_onclick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonUp {
            get {
                object obj = ResourceManager.GetObject("buttonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonUp_mouseover {
            get {
                object obj = ResourceManager.GetObject("buttonUp_mouseover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonUp_onclick {
            get {
                object obj = ResourceManager.GetObject("buttonUp_onclick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonZoomIn {
            get {
                object obj = ResourceManager.GetObject("buttonZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonZoomIn_MouseDown {
            get {
                object obj = ResourceManager.GetObject("buttonZoomIn_MouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonZoomIn_Mouseover {
            get {
                object obj = ResourceManager.GetObject("buttonZoomIn_Mouseover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonZoomOut {
            get {
                object obj = ResourceManager.GetObject("buttonZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonZoomOut_MouseDown {
            get {
                object obj = ResourceManager.GetObject("buttonZoomOut_MouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonZoomOut_MouseOver {
            get {
                object obj = ResourceManager.GetObject("buttonZoomOut_MouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circMazeBG {
            get {
                object obj = ResourceManager.GetObject("circMazeBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circMazeLogo {
            get {
                object obj = ResourceManager.GetObject("circMazeLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collections1 {
            get {
                object obj = ResourceManager.GetObject("collections1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collections1a {
            get {
                object obj = ResourceManager.GetObject("collections1a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CommandItemIcon {
            get {
                object obj = ResourceManager.GetObject("CommandItemIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap curvedWallIcon {
            get {
                object obj = ResourceManager.GetObject("curvedWallIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap del {
            get {
                object obj = ResourceManager.GetObject("del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dynamic_object {
            get {
                object obj = ResourceManager.GetObject("dynamic_object", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dynamic1 {
            get {
                object obj = ResourceManager.GetObject("Dynamic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; &lt;a href=&quot;Models.htm&quot;&gt;Models&lt;/a&gt; &amp;gt; Dynamic Models
        ///			&lt;br&gt;
        ///			&lt;br&gt;
        ///			Dynamic Models are objects the user can interact with to complete the maze, in addition to making the maze seem more  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dynamicmodels {
            get {
                return ResourceManager.GetString("Dynamicmodels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Editing a Maze
        ///			&lt;br /&gt;
        ///			&lt;br /&gt;
        ///Once an object has been placed, you can edit it in a number of ways. &lt;br&gt;
        ///To select an object, choose the &quot;Pointer&quot; tool, and click on the object. Other [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Editmaze {
            get {
                return ResourceManager.GetString("Editmaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap end {
            get {
                object obj = ResourceManager.GetObject("end", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Adding End Regions
        ///			&lt;br /&gt;
        ///			&lt;br /&gt;
        ///			End Regions define the successful completion of the maze. When the user enters an End Region, the maze disappears. If the maze is in a MazeList (s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Endregion {
            get {
                return ResourceManager.GetString("Endregion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EndRegion1 {
            get {
                object obj = ResourceManager.GetObject("EndRegion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floor {
            get {
                object obj = ResourceManager.GetObject("floor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floor1 {
            get {
                object obj = ResourceManager.GetObject("floor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floorIcon {
            get {
                object obj = ResourceManager.GetObject("floorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forumicon {
            get {
                object obj = ResourceManager.GetObject("forumicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forumicon1 {
            get {
                object obj = ResourceManager.GetObject("forumicon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Getting Started
        ///			&lt;br&gt;
        ///			&lt;br&gt;
        ///			&lt;P&gt;MazeMaker has a graphical user interface that allows you to sketch maps 
        ///			visually with the mouse. &lt;/P&gt;
        ///			&lt;P&gt;Near the top of the MazeMaker window [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GettingStarted {
            get {
                return ResourceManager.GetString("GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;br&gt;
        ///&lt;h1&gt; MazeMaker Help &lt;/h1&gt;
        ///
        ///Welcome to the MazeMaker Help home. Please select the topic you want to view.
        ///&lt;br&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;&lt;a href=Introduction.htm&gt;Introduction&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=GettingStarted.htm&gt;Getting Started&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ImageCollectionIcon {
            get {
                object obj = ResourceManager.GetObject("ImageCollectionIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemIcon {
            get {
                object obj = ResourceManager.GetObject("ImageItemIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Introduction
        ///			&lt;br /&gt;
        ///			&lt;br /&gt;
        ///MazeMaker is part of Maze Suite which is a complete set of tools that enables researchers to perform spatial
        ///and navigational behavior experiments within  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Keyboard Interface
        ///			&lt;br&gt;
        ///			&lt;br&gt;        
        ///        &lt;table border=1 width=90%&gt;
        ///        &lt;tr&gt;&lt;td&gt;&lt;i&gt;Keys&lt;/i&gt;&lt;/td&gt;&lt;td&gt;&lt;i&gt;Function&lt;/i&gt;&lt;/td&gt;&lt;/tr&gt;
        ///        &lt;tr&gt;&lt;td&gt;Ctrl + O &lt;/td&gt;&lt;td&gt; Open Files &lt;/td&gt;&lt;/tr&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Lights
        ///			&lt;br /&gt;
        ///			&lt;br /&gt;
        ///			Lights are another way (besides &lt;a href=&quot;Textures.htm&quot;&gt;Textures&lt;/a&gt; and &lt;a href=&quot;Models.htm&quot;&gt;Models&lt;/a&gt;) to increase the realism of a maze. Instead of general [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lights {
            get {
                return ResourceManager.GetString("Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap link {
            get {
                object obj = ResourceManager.GetObject("link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list1 {
            get {
                object obj = ResourceManager.GetObject("list1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ListItemsIcon {
            get {
                object obj = ResourceManager.GetObject("ListItemsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo1 {
            get {
                object obj = ResourceManager.GetObject("logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mazegen {
            get {
                object obj = ResourceManager.GetObject("mazegen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mazegen1 {
            get {
                object obj = ResourceManager.GetObject("mazegen1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mazegen2 {
            get {
                object obj = ResourceManager.GetObject("mazegen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MazeItemIcon {
            get {
                object obj = ResourceManager.GetObject("MazeItemIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; &lt;a href=Tools.htm&gt;Tools&lt;/a&gt; &amp;gt; MazeListBuilder
        ///
        ///&lt;br&gt;&lt;br&gt;&lt;br&gt;
        ///        &lt;b&gt;Function:&lt;/b&gt;&lt;i&gt;Create and edit maze lists.&lt;/i&gt; 
        ///        &lt;br&gt;&lt;br&gt;
        ///		The MazeListBuilder can be found under the &quot;Tools&quot; menu.
        ///		&lt;br [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MazeListBuilder {
            get {
                return ResourceManager.GetString("MazeListBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MazeListOptionsItemIcon {
            get {
                object obj = ResourceManager.GetObject("MazeListOptionsItemIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mazeMaker_500 {
            get {
                object obj = ResourceManager.GetObject("mazeMaker_500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon mazemaker1 {
            get {
                object obj = ResourceManager.GetObject("mazemaker1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mazeMakerBG {
            get {
                object obj = ResourceManager.GetObject("mazeMakerBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MazeMakerSplash1 {
            get {
                object obj = ResourceManager.GetObject("MazeMakerSplash1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MazeSuite {
            get {
                object obj = ResourceManager.GetObject("MazeSuite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MazeSuite_MouseOver {
            get {
                object obj = ResourceManager.GetObject("MazeSuite_MouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mazeWizardIcon {
            get {
                object obj = ResourceManager.GetObject("mazeWizardIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; &lt;a href=&quot;Models.htm&quot;&gt;Models&lt;/a&gt; &amp;gt; The Model Collection
        ///			&lt;br&gt;
        ///			&lt;br&gt;
        ///			In order to place external objects (or &quot;Models&quot;) into a maze, there have to bee objects in the Model Collection [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Modelcollection {
            get {
                return ResourceManager.GetString("Modelcollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ModelCollectionIcon {
            get {
                object obj = ResourceManager.GetObject("ModelCollectionIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Models
        ///&lt;br&gt;&lt;br&gt;
        ///Models are 3d objects that can be placed in a maze. There are two types of Models: Static and Dynamic models. 
        ///Static models can be used to create a more realistic environment, along with &lt;a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MultipleChoiceItemIcon {
            get {
                object obj = ResourceManager.GetObject("MultipleChoiceItemIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navControl_BG {
            get {
                object obj = ResourceManager.GetObject("navControl_BG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewMazeListIcon {
            get {
                object obj = ResourceManager.GetObject("NewMazeListIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap normal {
            get {
                object obj = ResourceManager.GetObject("normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PackageItemsIcon {
            get {
                object obj = ResourceManager.GetObject("PackageItemsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap panIcon {
            get {
                object obj = ResourceManager.GetObject("panIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseAudioIcon {
            get {
                object obj = ResourceManager.GetObject("PauseAudioIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play1 {
            get {
                object obj = ResourceManager.GetObject("Play1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayAudioIcon {
            get {
                object obj = ResourceManager.GetObject("PlayAudioIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RecordAudioItemIcon {
            get {
                object obj = ResourceManager.GetObject("RecordAudioItemIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectMazeBG {
            get {
                object obj = ResourceManager.GetObject("rectMazeBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectMazeLogo {
            get {
                object obj = ResourceManager.GetObject("rectMazeLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Removing Items
        ///			&lt;br&gt;&lt;br&gt;
        ///To remove items, simply select the item and press the &quot;Delete&quot; key (not the backspace) or the &quot;Delete&quot; button in the toolbar or &quot;Edit&quot; menu.&lt;br /&gt;&lt;br /&gt;
        ///Be caref [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Removingitems {
            get {
                return ResourceManager.GetString("Removingitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveas {
            get {
                object obj = ResourceManager.GetObject("saveas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Selecting Objects
        ///			&lt;br /&gt;
        ///			&lt;br /&gt;
        ///The most basic way to select an object is by clicking on it in &quot;Pointer&quot; mode. When selecting floors or End Regions, clicking the mouse will select al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Selectingobjects {
            get {
                return ResourceManager.GetString("Selectingobjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Adding the Start Position
        ///			&lt;br /&gt;
        ///			&lt;br /&gt;
        ///To set the starting position, select the &quot;Start Pos&quot; tool and click anywhere in the pane to set the starting point.&lt;br&gt;&lt;br&gt;
        ///Since there can b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Startposition {
            get {
                return ResourceManager.GetString("Startposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap static_object {
            get {
                object obj = ResourceManager.GetObject("static_object", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Static1 {
            get {
                object obj = ResourceManager.GetObject("Static1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; &lt;a href=&quot;Models.htm&quot;&gt;Models&lt;/a&gt; &amp;gt; Static Models
        ///			&lt;br&gt;
        ///			&lt;br&gt;
        ///			Static Models are simply static objects that were created in another program. To add a Static Object, select the &quot;Stat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Staticmodels {
            get {
                return ResourceManager.GetString("Staticmodels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Testing a Maze
        ///			&lt;br /&gt;
        ///			&lt;br /&gt;
        ///The &quot;Quick Run&quot; feature allows you to test the maze you are working on, by opening the MazeWalker application. This feature can be found in the toolbar o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Testingamaze {
            get {
                return ResourceManager.GetString("Testingamaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextItemIcon {
            get {
                object obj = ResourceManager.GetObject("TextItemIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///		&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;P&gt;
        ///			&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; &lt;a href=&quot;Textures.htm&quot;&gt;Textures&lt;/a&gt; &amp;gt; The Texture Collection
        ///			&lt;br /&gt;
        ///			&lt;br /&gt;
        ///			In order to apply textures, you must have images available for texturing. The Texture Collection is a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Texturecollection {
            get {
                return ResourceManager.GetString("Texturecollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Textures
        ///&lt;br&gt;&lt;br&gt;
        ///Textures are images that can be placed on ceilings, walls, and floors to make the maze environment feel more realistic.&lt;br&gt;They can be tiled or stretched over a surface.
        ///Like &lt;a href=&quot;Model [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Textures {
            get {
                return ResourceManager.GetString("Textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft Visual Studio .NET 7.1&quot;&gt;
        ///&lt;meta name=&quot;vs_targetSchema&quot; content=&quot;http://schemas.microsoft.com/intellisense/ie5&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;a href=&quot;Home.htm&quot;&gt;Home&lt;/a&gt; &amp;gt; Tools
        ///&lt;br&gt;&lt;br&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;&lt;a href=MazeListBuilder.htm&gt;Create Maze List&lt;/a&gt;&lt;/li&gt;
        ///
        ///&lt;/ul&gt;
        ///        &lt;br&gt;&lt;br&gt;&lt;br&gt;&lt;br&gt;&lt;br&gt;&lt;br&gt;&lt;br&gt;&lt;br&gt;&lt;br&gt;
        ///        &lt;hr&gt;
        ///        &lt;font size=2 color =red&gt;Pre-release document, subje [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap W_back {
            get {
                object obj = ResourceManager.GetObject("W_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap W_forward {
            get {
                object obj = ResourceManager.GetObject("W_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap W_home {
            get {
                object obj = ResourceManager.GetObject("W_home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall {
            get {
                object obj = ResourceManager.GetObject("wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall1 {
            get {
                object obj = ResourceManager.GetObject("wall1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wizard1 {
            get {
                object obj = ResourceManager.GetObject("Wizard1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wizard2 {
            get {
                object obj = ResourceManager.GetObject("Wizard2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XYZ_grid {
            get {
                object obj = ResourceManager.GetObject("XYZ_grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
